version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: electricity-db
    restart: always
    environment:
      POSTGRES_DB: electricity
      POSTGRES_USER: academy
      POSTGRES_PASSWORD: academy
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U academy -d electricity"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: electricity-backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://academy:academy@db:5432/electricity
    ports:
      - "3010:3000"

  frontend:
    build: ./frontend
    container_name: electricity-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "8080:80" # Nginx default

volumes:
  postgres_data:
