version: "3.8"

services:
  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    image: postgres:15-alpine
    container_name: electricity-db
    restart: always
    environment:
      POSTGRES_DB: electricity
      POSTGRES_USER: academy
      POSTGRES_PASSWORD: academy
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U academy -d electricity"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: electricity-backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://academy:academy@db:5432/electricity
    ports:
      - "3010:3010"
    labels:
      - traefik.enable=true
      - "traefik.http.routers.backend.rule=Host(`solita.backend.joniharju.fi`)"

  frontend:
    build:
      context: ./frontend
      args:
        VITE_BACKEND_URL: ${VITE_BACKEND_URL} # Pass the VITE_BACKEND_URL to the build
    container_name: electricity-frontend
    restart: always
    depends_on:
      - backend
    environment:
      - VITE_BACKEND_URL=${VITE_BACKEND_URL:-http://localhost:3010}
    ports:
      - "8081:80"

volumes:
  postgres_data:
